services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-utility-bills-bot
    restart: unless-stopped
    environment:
      - TelegramBot__Token=${TELEGRAM_BOT_TOKEN}
      - TelegramBot__AllowedUserIds=${ALLOWED_USER_IDS:-}
      - YandexDisk__Token=${YANDEX_DISK_TOKEN}
      - YandexDisk__RootFolder=Квитанции
    volumes:
      # Монтируем appsettings.json если хотите использовать файл вместо переменных окружения
      - ./appsettings.json:/app/appsettings.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

